import { PresetCollege } from '../types';
import { getFullMajorsList } from './commonMajors';

export const COLLEGES_PART_1: PresetCollege[] = [
  {
    id: 'princeton',
    name: 'Princeton University',
    shortName: 'Princeton',
    location: 'Princeton, NJ',
    color: '#E77500',
    emoji: '🐅',
    portalType: 'Common App',
    website: 'https://admission.princeton.edu',
    majorsUrl: 'https://uao.princeton.edu/academics/areas-study',
    acceptanceRate: '4.4%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (AB / BSE)',
      'Operations Research and Financial Engineering (ORFE)',
      'School of Public and International Affairs (SPIA)',
      'Economics',
      'Mechanical and Aerospace Engineering',
      'Molecular Biology',
      'Civil and Environmental Engineering',
      'Electrical and Computer Engineering',
      'Chemical and Biological Engineering',
      'Mathematics',
      'Physics',
      'Comparative Literature',
      'History',
      'Philosophy'
    ]),
    defaultSections: [
      { title: 'Common App Core & Main Essay', description: 'General personal background, activities, and 650-word personal essay.', category: 'essay', wordLimit: '650 words' },
      { title: 'Princeton Degree (AB vs BSE) & Academic Interests', description: 'Briefly explain what academic interests you plan to study and why.', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Princeton Short Essay: Extracurricular Passion', description: 'Briefly elaborate on an activity, hobby, or job that has been particularly meaningful.', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Princeton Short Essay: Civic Engagement & Service', description: 'Princeton has a longstanding commitment to service. How have you lived out this mission?', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Princeton Graded Written Paper Submission', description: 'Submit an official graded academic paper written for an English or History class with teacher marks.', category: 'academics' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'Official high school report, transcripts, and 2 academic recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'mit',
    name: 'Massachusetts Institute of Technology (MIT)',
    shortName: 'MIT',
    location: 'Cambridge, MA',
    color: '#A31F34',
    emoji: '⚙️',
    portalType: 'MIT Application',
    website: 'https://mitadmissions.org',
    majorsUrl: 'https://mitadmissions.org/discover/majors/',
    acceptanceRate: '3.9%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-05',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Course 6-3: Computer Science & Engineering',
      'Course 6-4: Artificial Intelligence & Decision Making',
      'Course 6-2: Electrical Engineering & Computer Science',
      'Course 2: Mechanical Engineering',
      'Course 18: Mathematics',
      'Course 8: Physics',
      'Course 20: Biological Engineering',
      'Course 16: Aerospace Engineering',
      'Course 10: Chemical Engineering',
      'Course 14: Economics',
      'Course 9: Brain & Cognitive Sciences',
      'Course 15: Management Sciences & Finance'
    ]),
    defaultSections: [
      { title: 'MIT Application Profile & Biographical Info', description: 'Direct MIT portal family, academic, and personal details.', category: 'general' },
      { title: 'MIT Essay 1: What You Do for the Pleasure of It', description: 'Describe something you do simply for the pleasure of it.', category: 'supplemental', wordLimit: '225 words' },
      { title: 'MIT Essay 2: Department or Field of Study', description: 'What department or program at MIT appeals to you and why?', category: 'supplemental', wordLimit: '225 words' },
      { title: 'MIT Essay 3: Contributing to Community & Culture', description: 'Describe the world you come from and how it shaped your dreams.', category: 'supplemental', wordLimit: '225 words' },
      { title: 'MIT Essay 4: Significant Challenge / Disappointment', description: 'Tell us about a challenge you faced and how you managed the situation.', category: 'supplemental', wordLimit: '225 words' },
      { title: 'MIT Essay 5: Collaboration & Building Bridges', description: 'Tell us about a time you collaborated with others to accomplish a goal.', category: 'supplemental', wordLimit: '225 words' },
      { title: 'Self-Reported Coursework Form (SRCF)', description: 'Direct high school calculus, physics, chemistry, and biology entry.', category: 'academics' },
      { title: 'Evaluations: 1 STEM + 1 Humanities Teacher', description: 'Mandatory 1 math/science teacher and 1 humanities/social science teacher.', category: 'recommendations' }
    ]
  },
  {
    id: 'harvard',
    name: 'Harvard University',
    shortName: 'Harvard',
    location: 'Cambridge, MA',
    color: '#A51C30',
    emoji: '🏛️',
    portalType: 'Common App',
    website: 'https://college.harvard.edu/admissions',
    majorsUrl: 'https://college.harvard.edu/academics/fields-study',
    acceptanceRate: '3.4%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Economics',
      'Government / Political Science',
      'Applied Mathematics',
      'Social Studies',
      'Integrative Biology',
      'Molecular & Cellular Biology',
      'Neuroscience',
      'History and Literature',
      'Bioengineering',
      'Electrical Engineering',
      'Psychology',
      'English'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Main application and 650-word personal statement.', category: 'essay', wordLimit: '650 words' },
      { title: 'Harvard Question 1: Life Experiences & Perspective', description: 'How have your life experiences shaped who you are today?', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Harvard Question 2: Intellectual Curiosity', description: 'Describe an intellectual experience that sparked your curiosity.', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Harvard Question 3: Top 3 Extracurriculars or Jobs', description: 'Elaborate on up to three activities or work experiences.', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Harvard Question 4: College Education Impact', description: 'How do you hope to use your college education to impact the world?', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Harvard Question 5: Top 3 Roommate Takeaways', description: 'Top 3 things your college roommate should know about you.', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Counselor Recommendation & 2 Teacher Evaluations', description: 'Official high school report and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    shortName: 'Stanford',
    location: 'Stanford, CA',
    color: '#8C1515',
    emoji: '🌲',
    portalType: 'Common App',
    website: 'https://admission.stanford.edu',
    majorsUrl: 'https://majors.stanford.edu',
    acceptanceRate: '3.6%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-05',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Symbolic Systems',
      'Management Science & Engineering (MS&E)',
      'Human Biology',
      'Economics',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Bioengineering',
      'Data Science',
      'Political Science',
      'International Relations',
      'Product Design',
      'Mathematical & Computational Science'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Core application profile and 650-word essay.', category: 'essay', wordLimit: '650 words' },
      { title: 'Stanford Short Questions (5 questions)', description: '5 short takes: Challenge society faces, Historical moment, 3 adjectives, etc.', category: 'supplemental', wordLimit: '5 × 50 words' },
      { title: 'Stanford Essay 1: Exciting Intellectual Experience', description: 'Reflect on an idea or experience that makes you genuinely excited about learning.', category: 'supplemental', wordLimit: '100–250 words' },
      { title: 'Stanford Essay 2: Letter to Future Roommate', description: 'Write a note that reveals something meaningful to your future roommate.', category: 'supplemental', wordLimit: '100–250 words' },
      { title: 'Stanford Essay 3: What Is Meaningful to You & Why?', description: 'Tell us what matters most to you and why.', category: 'supplemental', wordLimit: '100–250 words' },
      { title: 'Counselor Report & 2 Academic Teacher Letters', description: 'High school transcripts and evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'yale',
    name: 'Yale University',
    shortName: 'Yale',
    location: 'New Haven, CT',
    color: '#00356B',
    emoji: '🐶',
    portalType: 'Common App',
    website: 'https://admissions.yale.edu',
    majorsUrl: 'https://admissions.yale.edu/majors-and-academic-programs',
    acceptanceRate: '4.5%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Ethics, Politics, and Economics (EPE)',
      'Computer Science',
      'Global Affairs',
      'Economics',
      'History',
      'Molecular, Cellular, and Developmental Biology',
      'Political Science',
      'Applied Mathematics',
      'Biomedical Engineering',
      'English Language & Literature',
      'Neuroscience'
    ]),
    defaultSections: [
      { title: 'Common App Core Profile & Essay', description: 'Main application and 650-word personal essay.', category: 'essay', wordLimit: '650 words' },
      { title: 'Yale Academic Curiosity Short Answer', description: 'What academic areas currently excite you and why?', category: 'supplemental', wordLimit: '125 words' },
      { title: 'Yale 3 Short Takes', description: 'What course would you teach? What question do you want answered? What fills you with awe?', category: 'supplemental', wordLimit: '3 × 35 words' },
      { title: 'Yale Essay (Choose 1 of 2)', description: 'Engaging diverse perspectives OR an experience that sparked curiosity.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'School report, midyear report, and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'caltech',
    name: 'California Institute of Technology (Caltech)',
    shortName: 'Caltech',
    location: 'Pasadena, CA',
    color: '#FF6C0C',
    emoji: '🔬',
    portalType: 'Common App',
    website: 'https://admissions.caltech.edu',
    majorsUrl: 'https://www.admissions.caltech.edu/academics/majors-minors',
    acceptanceRate: '2.7%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-03',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Physics',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Bioengineering',
      'Computation and Neural Systems (CNS)',
      'Chemical Engineering',
      'Applied and Computational Mathematics',
      'Planetary Science & Astronomy',
      'Information and Data Sciences'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Application profile and 650-word essay.', category: 'essay' },
      { title: 'Caltech STEM Exploration & Curiosity Essay', description: 'Describe an experience where you applied STEM to explore a question.', category: 'supplemental', wordLimit: '200–400 words' },
      { title: 'Caltech Joy Outside of STEM Essay', description: 'Tell us about a hobby or pursuit outside of STEM that brings you joy.', category: 'supplemental', wordLimit: '100–250 words' },
      { title: 'Caltech Navigating Conflict & Collaboration', description: 'How have you navigated a difference of perspectives with a peer?', category: 'supplemental', wordLimit: '200–400 words' },
      { title: 'Evaluations: 1 STEM + 1 Humanities Teacher', description: 'Mandatory 1 math/science teacher and 1 humanities teacher.', category: 'recommendations' }
    ]
  },
  {
    id: 'duke',
    name: 'Duke University',
    shortName: 'Duke',
    location: 'Durham, NC',
    color: '#003087',
    emoji: '😈',
    portalType: 'Common App',
    website: 'https://admissions.duke.edu',
    majorsUrl: 'https://admissions.duke.edu/academics/majors-minors/',
    acceptanceRate: '6.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Biomedical Engineering (Pratt)',
      'Economics (Financial Economics)',
      'Public Policy Studies (Sanford)',
      'Biology / Pre-Med',
      'Mechanical Engineering',
      'Electrical and Computer Engineering',
      'Neuroscience',
      'Global Health',
      'Psychology'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Completed profile, activities, and 650-word essay.', category: 'essay', wordLimit: '650 words' },
      { title: 'Duke Trinity vs Pratt Academic Match Essay', description: 'What led you to apply to Trinity College of Arts & Sciences or Pratt Engineering?', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Duke Optional Prompt: Diverse Community & Perspective', description: 'Share how your background or unique perspective enriches our community.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Recommendation & 2 Teacher Evaluations', description: 'Official high school report and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'jhu',
    name: 'Johns Hopkins University (JHU)',
    shortName: 'Johns Hopkins',
    location: 'Baltimore, MD',
    color: '#002D72',
    emoji: '🥼',
    portalType: 'Common App',
    website: 'https://apply.jhu.edu',
    majorsUrl: 'https://apply.jhu.edu/academics/majors-and-minors/',
    acceptanceRate: '6.2%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Biomedical Engineering (BME)',
      'Public Health Studies',
      'Neuroscience',
      'Computer Science',
      'Molecular & Cellular Biology',
      'International Studies',
      'Economics',
      'Mechanical Engineering',
      'Chemical and Biomolecular Engineering',
      'Behavioral Biology'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Main application profile and personal statement.', category: 'essay', wordLimit: '650 words' },
      { title: 'JHU Collaboration & Problem Solving Essay', description: 'Tell us about a time you collaborated with others or dove deeply into an academic interest.', category: 'supplemental', wordLimit: '300–400 words' },
      { title: 'Counselor Recommendation & 2 Academic Teacher Letters', description: 'Secondary school report and teacher recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'northwestern',
    name: 'Northwestern University',
    shortName: 'Northwestern',
    location: 'Evanston, IL',
    color: '#4E2A84',
    emoji: '🟣',
    portalType: 'Common App',
    website: 'https://admissions.northwestern.edu',
    majorsUrl: 'https://admissions.northwestern.edu/academics/majors-minors.html',
    acceptanceRate: '7.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-03',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Journalism (Medill)',
      'Economics',
      'Computer Science (McCormick / Weinberg)',
      'Biomedical Engineering',
      'Theatre & Performance Studies',
      'Industrial Engineering & Management Sciences',
      'Radio/Television/Film (RTVF)',
      'Biological Sciences',
      'Political Science',
      'Music Performance (Bienen)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: '650-word personal essay and standard activities.', category: 'essay' },
      { title: 'Northwestern Essay 1: Why Northwestern & School Match', description: 'What aspects of Northwestern’s academic community and student life resonate with you?', category: 'supplemental', wordLimit: '300 words' },
      { title: 'Northwestern Optional Prompt: Community Perspective', description: 'How have your background, experiences, or communities shaped what you hope to discover?', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'School report, transcripts, and teacher recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania (UPenn)',
    shortName: 'Penn',
    location: 'Philadelphia, PA',
    color: '#011F5B',
    emoji: '🔔',
    portalType: 'Common App',
    website: 'https://admissions.upenn.edu',
    majorsUrl: 'https://admissions.upenn.edu/academics/majors-minors',
    acceptanceRate: '5.8%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-05',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Wharton: Finance',
      'Wharton: Business Economics & Public Policy',
      'Wharton: Management & Entrepreneurship',
      'Computer and Information Science (SEAS)',
      'Bioengineering',
      'Philosophy, Politics and Economics (PPE)',
      'Nursing (BSN)',
      'Economics (College of Arts & Sciences)',
      'Jerome Fisher M&T (Dual Degree)',
      'Huntsman Program in International Studies & Business',
      'Vagelos Program in Life Sciences & Management (LSM)',
      'Mechanical Engineering and Applied Mechanics'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Standard 650-word essay and 10 activities.', category: 'essay', wordLimit: '650 words' },
      { title: 'UPenn Essay 1: Thank You Letter', description: 'Write a thank-you note to someone you have not yet thanked and would like to acknowledge.', category: 'supplemental', wordLimit: '150–200 words' },
      { title: 'UPenn Essay 2: Undergraduate School Academic Exploration', description: 'How will you explore your intellectual interests at your chosen undergraduate school at Penn?', category: 'supplemental', wordLimit: '450 words' },
      { title: 'Counselor Recommendation & 2 Academic Teacher Letters', description: 'High school transcripts and teacher evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'cornell',
    name: 'Cornell University',
    shortName: 'Cornell',
    location: 'Ithaca, NY',
    color: '#B31B1B',
    emoji: '🐻',
    portalType: 'Common App',
    website: 'https://admissions.cornell.edu',
    majorsUrl: 'https://admissions.cornell.edu/learn/academics/fields-study',
    acceptanceRate: '7.3%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Hotel Administration (Nolan School)',
      'Applied Economics and Management (Dyson)',
      'Computer Science (Engineering / Arts & Sciences)',
      'Industrial and Labor Relations (ILR)',
      'Biological Sciences (CALS / Arts & Sciences)',
      'Mechanical Engineering',
      'Architecture (B.Arch, AAP)',
      'Biomedical Engineering',
      'Animal Science',
      'Government / Political Science',
      'Environment & Sustainability'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: '650-word personal essay and core profile.', category: 'essay' },
      { title: 'Cornell College-Specific Supplemental Essay', description: 'Detailed essay tailored specifically to the Cornell college to which you are applying.', category: 'supplemental', wordLimit: '650 words' },
      { title: 'Counselor Report & 2 Academic Teacher Letters', description: 'Official high school transcript and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'uchicago',
    name: 'University of Chicago (UChicago)',
    shortName: 'UChicago',
    location: 'Chicago, IL',
    color: '#800000',
    emoji: '📚',
    portalType: 'Common App',
    website: 'https://collegeadmissions.uchicago.edu',
    majorsUrl: 'https://collegeadmissions.uchicago.edu/academics/programs-study',
    acceptanceRate: '4.8%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Economics (Business Economics / Data Economics)',
      'Computer Science',
      'Public Policy Studies',
      'Mathematics',
      'Biological Sciences / Pre-Med',
      'Physics',
      'Law, Letters, and Society',
      'Molecular Engineering',
      'Political Science',
      'Philosophy'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: '650-word personal essay and activities.', category: 'essay' },
      { title: 'UChicago Extended Essay (Famous Quirky Prompt)', description: 'Choose from one of UChicago’s creative, unconventional prompt options.', category: 'supplemental', wordLimit: '500 words' },
      { title: 'UChicago Why College Essay', description: 'How does the University of Chicago satisfy your desire for a particular kind of learning?', category: 'supplemental', wordLimit: '250 words' },
      { title: '2 Academic Teacher Evaluations & Counselor Report', description: 'School report, transcripts, and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'brown',
    name: 'Brown University',
    shortName: 'Brown',
    location: 'Providence, RI',
    color: '#4E3629',
    emoji: '🐻',
    portalType: 'Common App',
    website: 'https://admission.brown.edu',
    majorsUrl: 'https://admission.brown.edu/learning-at-brown/concentrations',
    acceptanceRate: '5.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-03',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Economics',
      'Program in Liberal Medical Education (PLME 8-year)',
      'Applied Mathematics',
      'International and Public Affairs (IAPA)',
      'Biology',
      'Biomedical Engineering',
      'Cognitive Neuroscience',
      'Literary Arts / Creative Writing',
      'Modern Culture and Media'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word essay and profile.', category: 'essay' },
      { title: 'Brown Open Curriculum Essay: How Will You Explore?', description: 'How will you take advantage of the freedom of the Open Curriculum?', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Brown Community Essay: Where You Come From', description: 'Share how your growing up or background influenced who you are today.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Brown Joy in Learning Short Prompt', description: 'Tell us about a topic or concept that brings you intense intellectual excitement.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Optional 2-Minute Video Introduction', description: 'Personal, unscripted 2-minute video introduction.', category: 'portfolio' },
      { title: 'Counselor Report & 2 Academic Teacher Letters', description: 'High school transcripts and teacher evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'columbia',
    name: 'Columbia University',
    shortName: 'Columbia',
    location: 'New York, NY',
    color: '#1D63B8',
    emoji: '🗽',
    portalType: 'Common App',
    website: 'https://undergrad.admissions.columbia.edu',
    majorsUrl: 'https://undergrad.admissions.columbia.edu/academics/programs',
    acceptanceRate: '3.9%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (SEAS / CC)',
      'Economics & Financial Economics',
      'Political Science / International Relations',
      'Biomedical Engineering',
      'Applied Mathematics',
      'English and Comparative Literature',
      'Neuroscience and Behavior',
      'History',
      'Architecture',
      'Operations Research'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: '650-word personal statement and activities.', category: 'essay' },
      { title: 'Columbia List Question: Cultural & Intellectual Media', description: 'List the required readings, books read for pleasure, podcasts, and exhibits you enjoyed.', category: 'supplemental', wordLimit: '100 words' },
      { title: 'Columbia Essay 1: Why Columbia & Academic Match', description: 'Why are you drawn to the specific undergraduate college at Columbia?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Columbia Essay 2: What Sparks Your Curiosity Outside School?', description: 'What brings you joy or sparks your curiosity outside the classroom?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Columbia Essay 3: Contributing to Columbia Community', description: 'How do you envision contributing to our diverse and collaborative student body?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'Secondary school report and evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'dartmouth',
    name: 'Dartmouth College',
    shortName: 'Dartmouth',
    location: 'Hanover, NH',
    color: '#00693E',
    emoji: '🌲',
    portalType: 'Common App',
    website: 'https://admissions.dartmouth.edu',
    majorsUrl: 'https://admissions.dartmouth.edu/academics/departments-programs',
    acceptanceRate: '6.2%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Economics',
      'Government',
      'Computer Science',
      'Engineering Sciences (Thayer)',
      'Biology',
      'Psychological and Brain Sciences',
      'History',
      'Environmental Studies',
      'Quantitative Social Science (QSS)'
    ]),
    defaultSections: [
      { title: 'Common App Core Profile & Essay', description: 'Standard application profile and 650-word essay.', category: 'essay' },
      { title: 'Dartmouth Why College Essay', description: 'What has led you to apply to Dartmouth, and how do you plan to use our resources?', category: 'supplemental', wordLimit: '100 words' },
      { title: 'Dartmouth Creative Prompt (Choose 1 of 6)', description: 'Answer one of Dartmouth’s thought-provoking supplemental prompts.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Peer Recommendation & 2 Teacher Letters', description: 'Dartmouth strongly encourages a letter from a peer or classmate.', category: 'recommendations' }
    ]
  },
  {
    id: 'ucla',
    name: 'UCLA (University of California, Los Angeles)',
    shortName: 'UCLA',
    location: 'Los Angeles, CA',
    color: '#2774AE',
    emoji: '🌴',
    portalType: 'UC Application',
    website: 'https://admission.ucla.edu',
    majorsUrl: 'https://admission.ucla.edu/explore/majors',
    acceptanceRate: '9.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'Computer Science (Samueli)',
      'Computer Science and Engineering (CSE)',
      'Business Economics (BizEcon)',
      'Biology / Pre-Med',
      'Psychobiology',
      'Mechanical Engineering',
      'Electrical Engineering',
      'Film and Television (TFT)',
      'Psychology',
      'Political Science',
      'Data Theory',
      'Computational and Systems Biology',
      'Nursing (BS)'
    ]),
    defaultSections: [
      { title: 'UC Application Base Profile & A-G History', description: '9th-12th coursework, California A-G alignment, and grades.', category: 'academics' },
      { title: 'UC Activities & Awards (20 slots)', description: 'Extracurriculars, volunteer hours, and work experiences.', category: 'general' },
      { title: '4 Personal Insight Questions (PIQs)', description: 'Four 350-word essays chosen from the 8 official University of California prompts.', category: 'essay', wordLimit: '4 × 350 words' },
      { title: 'Specialty School Supplement (TFT / Arts / Music / Nursing)', description: 'Required portfolio, audition, or supplemental essays if applying to specialty schools.', category: 'portfolio' }
    ]
  },
  {
    id: 'uc_berkeley',
    name: 'UC Berkeley (University of California, Berkeley)',
    shortName: 'UC Berkeley',
    location: 'Berkeley, CA',
    color: '#003262',
    emoji: '🐻',
    portalType: 'UC Application',
    website: 'https://admissions.berkeley.edu',
    majorsUrl: 'https://admissions.berkeley.edu/academics/majors-and-minors/',
    acceptanceRate: '11.5%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'Electrical Engineering & Computer Sciences (EECS)',
      'Computer Science (College of Computing, Data Science, and Society)',
      'Data Science',
      'Business Administration (Haas Spieker 4-Year)',
      'Mechanical Engineering',
      'Bioengineering',
      'Economics',
      'Molecular & Cell Biology (MCB)',
      'Integrative Biology',
      'Political Science',
      'Management, Entrepreneurship, & Technology (M.E.T.)',
      'Global Management Program (GMP Haas)'
    ]),
    defaultSections: [
      { title: 'UC Application Base Profile & A-G Coursework', description: 'Complete 9th-12th high school coursework and grades.', category: 'academics' },
      { title: 'UC Activities & Awards Log', description: '20 entries covering leadership, work, and community commitments.', category: 'general' },
      { title: 'PIQ 1: Leadership Experience', description: 'Describe an example of your leadership experience.', category: 'essay', wordLimit: '350 words' },
      { title: 'PIQ 2: Creative Expression', description: 'Describe how you express your creative side.', category: 'essay', wordLimit: '350 words' },
      { title: 'PIQ 3: Greatest Talent / Skill', description: 'Describe how you have developed and demonstrated your greatest talent.', category: 'essay', wordLimit: '350 words' },
      { title: 'PIQ 4: Educational Opportunity or Barrier', description: 'Describe educational opportunities taken or barriers overcome.', category: 'essay', wordLimit: '350 words' },
      { title: 'Haas / M.E.T. Supplemental Video & Essays', description: 'Additional invited video and essays for direct business and dual degree admits.', category: 'supplemental' }
    ]
  },
  {
    id: 'rice',
    name: 'Rice University',
    shortName: 'Rice',
    location: 'Houston, TX',
    color: '#00205B',
    emoji: '🦉',
    portalType: 'Common App',
    website: 'https://admission.rice.edu',
    majorsUrl: 'https://admission.rice.edu/academics/majors-minors',
    acceptanceRate: '7.7%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-04',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science',
      'Bioengineering',
      'Sport Management',
      'Mechanical Engineering',
      'Business (Jones Undergraduate)',
      'Economics',
      'Kinesiology & Health Sciences',
      'Architecture (B.Arch 6-year)',
      'Electrical and Computer Engineering',
      'Biosciences / Biochemistry'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Completed profile and 650-word personal statement.', category: 'essay' },
      { title: 'Rice Academic Interests & School Match Essay', description: 'What motivated you to apply to the undergraduate school you selected at Rice?', category: 'supplemental', wordLimit: '500 words' },
      { title: 'Rice Residential College & Community Essay', description: 'How will you contribute to Rice’s residential college system and culture?', category: 'supplemental', wordLimit: '500 words' },
      { title: 'The Rice "The Box" Image Upload', description: 'Submit an image of something that appeals to you or tells us about you.', category: 'portfolio' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'Transcripts and teacher recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'vanderbilt',
    name: 'Vanderbilt University',
    shortName: 'Vanderbilt',
    location: 'Nashville, TN',
    color: '#866D4B',
    emoji: '⚓',
    portalType: 'Common App',
    website: 'https://admissions.vanderbilt.edu',
    majorsUrl: 'https://admissions.vanderbilt.edu/academics/majors/',
    acceptanceRate: '5.6%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Human & Organizational Development (Peabody)',
      'Economics',
      'Computer Science',
      'Biomedical Engineering',
      'Medicine, Health, & Society (MHS)',
      'Political Science',
      'Mechanical Engineering',
      'Musical Arts (Blair)',
      'Neuroscience',
      'Secondary Education'
    ]),
    defaultSections: [
      { title: 'Common App Core Profile & Essay', description: 'Standard application profile and 650-word essay.', category: 'essay' },
      { title: 'Vanderbilt Extracurricular / Work Elaboration', description: 'Briefly elaborate on one of your extracurricular activities or work experiences.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Recommendation & 2 Academic Teacher Letters', description: 'Official secondary school report and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'notre_dame',
    name: 'University of Notre Dame',
    shortName: 'Notre Dame',
    location: 'Notre Dame, IN',
    color: '#0C2340',
    emoji: '☘️',
    portalType: 'Common App',
    website: 'https://admissions.nd.edu',
    majorsUrl: 'https://admissions.nd.edu/academics/majors-minors/',
    acceptanceRate: '11.9%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Finance (Mendoza)',
      'Accounting (Mendoza)',
      'Computer Science',
      'Mechanical Engineering',
      'Biological Sciences / Pre-Med',
      'Political Science',
      'Economics',
      'Architecture (5-year B.Arch)',
      'Aerospace Engineering',
      'Marketing'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Application profile and 650-word personal statement.', category: 'essay' },
      { title: 'Notre Dame Short Essay 1: Force for Good', description: 'What is one way you hope to be a force for good in the world?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Notre Dame Short Essay 2 (Choose 1 of 4)', description: 'Select one prompt reflecting dialogue, tradition, community, or purpose.', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Counselor Recommendation & 1-2 Teacher Letters', description: 'Transcripts and academic evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'umich',
    name: 'University of Michigan - Ann Arbor',
    shortName: 'UMich',
    location: 'Ann Arbor, MI',
    color: '#00274C',
    emoji: '〽️',
    portalType: 'Common App',
    website: 'https://admissions.umich.edu',
    majorsUrl: 'https://admissions.umich.edu/academics/majors-degrees',
    acceptanceRate: '17.7%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Business Administration (Stephen M. Ross)',
      'Computer Science (Engineering / LSA)',
      'Mechanical Engineering',
      'Information (BS in Information, BSI)',
      'Biomedical Engineering',
      'Economics',
      'Political Science',
      'Biopsychology, Cognition, and Neuroscience (BCN)',
      'Aerospace Engineering',
      'Industrial and Operations Engineering (IOE)',
      'Data Science',
      'Nursing (BSN)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Main Essay', description: '650-word personal statement and activities log.', category: 'essay' },
      { title: 'UMich Essay 1: Community Connection', description: 'Describe a community you belong to and your place within it.', category: 'supplemental', wordLimit: '300 words' },
      { title: 'UMich Essay 2: Why College / School Curriculum Match', description: 'Describe the unique qualities that attract you to the specific undergraduate College or School at U-M.', category: 'supplemental', wordLimit: '550 words' },
      { title: 'Ross Business Admissions Portfolio (if applicable)', description: 'Required business artifact and case study prompt for Ross applicants.', category: 'portfolio' },
      { title: 'Counselor Recommendation & 1 Teacher Evaluation', description: 'Official high school report and recommendation.', category: 'recommendations' }
    ]
  },
  {
    id: 'georgetown',
    name: 'Georgetown University',
    shortName: 'Georgetown',
    location: 'Washington, DC',
    color: '#041E42',
    emoji: '🏛️',
    portalType: 'Georgetown Application',
    website: 'https://uadmissions.georgetown.edu',
    majorsUrl: 'https://uadmissions.georgetown.edu/academics/majors/',
    acceptanceRate: '12.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-10',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'International Politics (Walsh SFS)',
      'Finance (McDonough)',
      'Government',
      'International Political Economy (SFS)',
      'Computer Science',
      'Global Health (School of Health)',
      'Marketing (McDonough)',
      'Economics',
      'Culture and Politics (SFS)',
      'Nursing (BSN)'
    ]),
    defaultSections: [
      { title: 'Georgetown Application & Profile Part 1 & 2', description: 'Standalone Georgetown application portal.', category: 'general' },
      { title: 'Georgetown Extracurricular Essay', description: 'Briefly elaborate on an activity that has helped you grow as an individual.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Georgetown School-Specific Essay (SFS, MSB, CAS, SOH)', description: 'Tailored essay explaining passion for your chosen undergraduate school.', category: 'supplemental', wordLimit: '1 page' },
      { title: 'Alumni Interview', description: 'Mandatory interview with assigned Georgetown alumni admissions committee.', category: 'general' },
      { title: 'Teacher Recommendations & Secondary School Report', description: 'Official transcripts and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'unc',
    name: 'UNC Chapel Hill',
    shortName: 'UNC',
    location: 'Chapel Hill, NC',
    color: '#7BAFD4',
    emoji: '🐏',
    portalType: 'Common App',
    website: 'https://admissions.unc.edu',
    majorsUrl: 'https://admissions.unc.edu/explore/academics/majors-and-minors/',
    acceptanceRate: '16.8%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-10-15',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Business Administration (Kenan-Flagler)',
      'Computer Science',
      'Media and Journalism (Hussman)',
      'Biology / Pre-Med',
      'Health Policy and Management (Gillings Public Health)',
      'Economics',
      'Political Science',
      'Psychology & Neuroscience',
      'Biostatistics',
      'Environmental Health Sciences'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'UNC Short Answer 1: Intellectual or Personal Growth', description: 'Describe an aspect of your identity, passion, or perspective that enriches our community.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'UNC Short Answer 2: Expanding Your Horizons', description: 'Discuss a time when you stepped outside your comfort zone.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Recommendation & 1 Academic Teacher Letter', description: 'Secondary school report and teacher evaluation.', category: 'recommendations' }
    ]
  },
  {
    id: 'emory',
    name: 'Emory University',
    shortName: 'Emory',
    location: 'Atlanta, GA',
    color: '#002878',
    emoji: '🦅',
    portalType: 'Common App',
    website: 'https://apply.emory.edu',
    majorsUrl: 'https://apply.emory.edu/discover/academics/majors-and-minors.html',
    acceptanceRate: '11.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Business Administration (Goizueta BBA)',
      'Biology / Pre-Med',
      'Neuroscience and Behavioral Biology (NBB)',
      'Economics',
      'Quantitative Sciences (QTM)',
      'Computer Science',
      'Psychology',
      'Political Science',
      'Nursing (Nell Hodgson Woodruff)',
      'Human Health'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard application profile and 650-word essay.', category: 'essay' },
      { title: 'Emory Campus Selection Essay (Atlanta vs Oxford College)', description: 'What academic interests or community aspects motivate your campus preference?', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Emory Reflection Prompt (Choose 1 of 2)', description: 'Reflect on a book, work of art, or community experience that inspired you.', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'Transcripts and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'uva',
    name: 'University of Virginia (UVA)',
    shortName: 'UVA',
    location: 'Charlottesville, VA',
    color: '#232D4B',
    emoji: '⚔️',
    portalType: 'Common App',
    website: 'https://admission.virginia.edu',
    majorsUrl: 'https://admission.virginia.edu/academics/majors',
    acceptanceRate: '16.3%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Commerce (McIntire School of Commerce)',
      'Computer Science (Engineering / College)',
      'Economics',
      'Biomedical Engineering',
      'Political Science / Foreign Affairs',
      'Leadership and Public Policy (Batten)',
      'Kinesiology',
      'Architecture (Urban & Environmental Planning)',
      'Civil & Environmental Engineering',
      'Nursing (BSN)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Essay', description: 'Standard 650-word personal statement.', category: 'essay' },
      { title: 'UVA School-Specific Academic Essay', description: 'Explain your interest in the specific school (College, Engineering, Architecture, Nursing, Kinesiology).', category: 'supplemental', wordLimit: '250 words' },
      { title: 'UVA Community & Perspective Essay', description: 'How do your background, perspective, or life experiences enrich UVA?', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Recommendation & 1-2 Teacher Letters', description: 'Transcripts and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'washu',
    name: 'Washington University in St. Louis (WashU)',
    shortName: 'WashU',
    location: 'St. Louis, MO',
    color: '#A51890',
    emoji: '🐻',
    portalType: 'Common App',
    website: 'https://admissions.wustl.edu',
    majorsUrl: 'https://admissions.wustl.edu/academics/majors-and-minors/',
    acceptanceRate: '11.8%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Finance (Olin Business School)',
      'Computer Science (McKelvey Engineering)',
      'Biomedical Engineering',
      'Biology / Neuroscience (Pre-Med)',
      'Psychological & Brain Sciences',
      'Architecture & Design (Sam Fox)',
      'Economics and Strategy',
      'Mechanical Engineering',
      'Healthcare Management',
      'Philosophy-Neuroscience-Psychology (PNP)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'WashU Academic Division Match Essay', description: 'Tell us about your academic interests and why you want to study at WashU.', category: 'supplemental', wordLimit: '200 words' },
      { title: 'Counselor Recommendation & 1 Academic Teacher Letter', description: 'High school report and teacher evaluation.', category: 'recommendations' }
    ]
  },
  {
    id: 'uc_davis',
    name: 'UC Davis',
    shortName: 'UC Davis',
    location: 'Davis, CA',
    color: '#002855',
    emoji: '🐴',
    portalType: 'UC Application',
    website: 'https://www.ucdavis.edu/admissions',
    majorsUrl: 'https://www.ucdavis.edu/majors',
    acceptanceRate: '37.3%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'Animal Science / Pre-Vet',
      'Biological Sciences',
      'Computer Science (College of Letters and Science)',
      'Computer Science and Engineering (CSE)',
      'Managerial Economics',
      'Biomedical Engineering',
      'Viticulture and Enology (Wine Science)',
      'Psychology',
      'Food Science',
      'Mechanical Engineering',
      'Biotechnology'
    ]),
    defaultSections: [
      { title: 'UC Application Base Profile & Academic History', description: 'A-G high school courses and grades.', category: 'academics' },
      { title: 'UC Activities & Awards (20 slots)', description: 'Activities, leadership, and honors log.', category: 'general' },
      { title: '4 Personal Insight Questions (PIQs)', description: 'Four 350-word responses chosen from the 8 official prompts.', category: 'essay', wordLimit: '4 × 350 words' }
    ]
  },
  {
    id: 'ucsd',
    name: 'UC San Diego (UCSD)',
    shortName: 'UC San Diego',
    location: 'La Jolla, CA',
    color: '#182B49',
    emoji: '🔱',
    portalType: 'UC Application',
    website: 'https://admissions.ucsd.edu',
    majorsUrl: 'https://admissions.ucsd.edu/academics/majors.html',
    acceptanceRate: '24.7%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'Computer Science and Engineering (CSE)',
      'Data Science (Halıcıoğlu Data Science Institute)',
      'Bioengineering / Biotechnology',
      'Marine Biology (Scripps Institution of Oceanography)',
      'Cognitive Science (Machine Learning / Design)',
      'Molecular and Cell Biology',
      'Economics',
      'Mechanical and Aerospace Engineering',
      'International Studies',
      'Human Biology'
    ]),
    defaultSections: [
      { title: 'UC Application Profile & A-G Courses', description: 'Coursework matching and letter grades.', category: 'academics' },
      { title: 'UCSD 8 Colleges Ranking Preference', description: 'Rank order preference of Revelle, Muir, Marshall, Warren, ERC, Sixth, Seventh, and Eighth College.', category: 'general' },
      { title: '4 Personal Insight Questions (PIQs)', description: 'Four 350-word essays from the official UC prompts.', category: 'essay', wordLimit: '4 × 350 words' },
      { title: 'Activities & Awards Portfolio', description: '20 entries for extracurriculars, jobs, and recognitions.', category: 'general' }
    ]
  },
  {
    id: 'uf',
    name: 'University of Florida (UF)',
    shortName: 'Florida',
    location: 'Gainesville, FL',
    color: '#0021A5',
    emoji: '🐊',
    portalType: 'Common App',
    website: 'https://admissions.ufl.edu',
    majorsUrl: 'https://catalog.ufl.edu/UGRD/programs/',
    acceptanceRate: '23.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (Engineering / Liberal Arts)',
      'Finance (Warrington)',
      'Mechanical Engineering',
      'Biomedical Engineering',
      'Biology / Pre-Med',
      'Journalism & Telecommunication',
      'Applied Physiology and Kinesiology',
      'Agricultural and Life Sciences',
      'Psychology',
      'Nursing (BSN)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'UF SSAR (Student Self-Reported Academic Record)', description: 'Mandatory completion of Florida SSAR coursework reporting portal.', category: 'academics' },
      { title: 'UF Honors Program Application Essay (Optional)', description: 'Honors program supplemental questions.', category: 'supplemental' }
    ]
  },
  {
    id: 'usc',
    name: 'University of Southern California (USC)',
    shortName: 'USC',
    location: 'Los Angeles, CA',
    color: '#990000',
    emoji: '✌️',
    portalType: 'Common App',
    website: 'https://admission.usc.edu',
    majorsUrl: 'https://admission.usc.edu/explore/academics/majors-and-minors/',
    acceptanceRate: '9.9%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-15',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Business Administration (Marshall School of Business)',
      'Computer Science (Viterbi School of Engineering)',
      'Cinema & Media Studies / Film Production (SCA)',
      'Interactive Media & Games (SCA)',
      'Music Industry & Performance (Thornton)',
      'Communication (Annenberg)',
      'Biomedical Engineering',
      'Arts, Technology, and Business of Innovation (Iovine & Young)',
      'Real Estate Development (Price)',
      'Architecture (B.Arch)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Standard 650-word essay and activities.', category: 'essay' },
      { title: 'USC Academic Major Essay', description: 'Describe how you plan to pursue your academic interests at USC.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'USC 10 Quick Takes', description: '10 fun short answers: Dream job, Favorite book, Movie, Theme song, Snack, etc.', category: 'supplemental', wordLimit: '10 × 100 chars' },
      { title: 'SCA / Thornton / Roski / Iovine & Young Portfolio (if applicable)', description: 'Mandatory creative portfolio or audition for arts majors.', category: 'portfolio' },
      { title: 'Counselor Recommendation & 1 Academic Teacher Letter', description: 'Transcripts and recommendation.', category: 'recommendations' }
    ]
  },
  {
    id: 'ut_austin',
    name: 'University of Texas at Austin (UT Austin)',
    shortName: 'UT Austin',
    location: 'Austin, TX',
    color: '#BF5700',
    emoji: '🤘',
    portalType: 'Common App',
    website: 'https://admissions.utexas.edu',
    majorsUrl: 'https://admissions.utexas.edu/explore/academics/',
    acceptanceRate: '18.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-12-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Business Administration (McCombs)',
      'Canfield Business Honors Program (CBHP)',
      'Computer Science (Turing Scholars)',
      'Biomedical Engineering (Cockrell)',
      'Electrical and Computer Engineering (ECE)',
      'Mechanical Engineering',
      'Radio-Television-Film (Moody)',
      'Plan II Honors Program',
      'Nursing (BSN)',
      'Economics',
      'Biology / Pre-Med'
    ]),
    defaultSections: [
      { title: 'Common App Core / UT Topic A Essay', description: 'Tell us your story. What unique opportunities or challenges shaped who you are?', category: 'essay', wordLimit: '500–700 words' },
      { title: 'UT Short Answer 1: Why First-Choice Major?', description: 'Explain why you are applying to the specific college/school and major.', category: 'supplemental', wordLimit: '250–300 words' },
      { title: 'UT Short Answer 2: Leadership & Impact', description: 'Describe an example of your leadership within family, school, or community.', category: 'supplemental', wordLimit: '250–300 words' },
      { title: 'UT Short Answer 3: Contributions to Forty Acres', description: 'How will your distinctive experiences contribute to our diverse community?', category: 'supplemental', wordLimit: '250–300 words' },
      { title: 'Expanded High School Resume', description: 'Detailed multi-page resume documenting all high school activities.', category: 'general' },
      { title: 'High School Transcript & Class Rank Verification', description: 'Official high school transcript and Texas auto-admit verification.', category: 'academics' }
    ]
  },
  {
    id: 'georgia_tech',
    name: 'Georgia Institute of Technology (Georgia Tech)',
    shortName: 'Georgia Tech',
    location: 'Atlanta, GA',
    color: '#B3A369',
    emoji: '🐝',
    portalType: 'Common App',
    website: 'https://admission.gatech.edu',
    majorsUrl: 'https://admission.gatech.edu/explore/academics/degrees',
    acceptanceRate: '16.0%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (College of Computing)',
      'Mechanical Engineering',
      'Industrial and Systems Engineering (ISyE #1 Nationally)',
      'Aerospace Engineering',
      'Electrical and Computer Engineering',
      'Biomedical Engineering (Wallace H. Coulter)',
      'Business Administration (Scheller)',
      'Computational Media',
      'Chemical and Biomolecular Engineering',
      'Civil Engineering'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'Georgia Tech Why Major Essay', description: 'Why are you interested in studying your chosen major at Georgia Tech?', category: 'supplemental', wordLimit: '300 words' },
      { title: 'Official SAT / ACT Score Reporting', description: 'Mandatory test reporting required by Georgia University System.', category: 'testing' },
      { title: 'Counselor Recommendation & High School Transcript', description: 'Official secondary school report.', category: 'recommendations' }
    ]
  },
  {
    id: 'uc_irvine',
    name: 'UC Irvine (UCI)',
    shortName: 'UC Irvine',
    location: 'Irvine, CA',
    color: '#0064A4',
    emoji: '🐜',
    portalType: 'UC Application',
    website: 'https://admissions.uci.edu',
    majorsUrl: 'https://admissions.uci.edu/discover/majors-minors/',
    acceptanceRate: '25.7%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'Computer Science (Donald Bren School of ICS)',
      'Software Engineering (Bren ICS)',
      'Business Administration (Paul Merage)',
      'Biomedical Engineering',
      'Nursing Science (BS)',
      'Biological Sciences',
      'Mechanical Engineering',
      'Criminology, Law and Society',
      'Data Science (Bren ICS)',
      'Public Health Sciences',
      'Pharmaceutical Sciences'
    ]),
    defaultSections: [
      { title: 'UC Application Base Profile & A-G Courses', description: 'Comprehensive high school coursework and grades.', category: 'academics' },
      { title: 'UC Activities & Awards (20 slots)', description: 'Leadership, work experience, awards, and extracurriculars.', category: 'general' },
      { title: '4 Personal Insight Questions (PIQs)', description: 'Four 350-word essays chosen from the official UC prompts.', category: 'essay', wordLimit: '4 × 350 words' }
    ]
  },
  {
    id: 'ucsb',
    name: 'UC Santa Barbara (UCSB)',
    shortName: 'UC Santa Barbara',
    location: 'Santa Barbara, CA',
    color: '#003660',
    emoji: '🌊',
    portalType: 'UC Application',
    website: 'https://admissions.sa.ucsb.edu',
    majorsUrl: 'https://admissions.sa.ucsb.edu/majors',
    acceptanceRate: '27.9%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2026-11-30',
    defaultTargetBufferDays: 10,
    majors: getFullMajorsList([
      'College of Creative Studies (CCS Computing / Physics)',
      'Computer Science (College of Engineering)',
      'Economics & Accounting',
      'Mechanical Engineering',
      'Chemical Engineering',
      'Aquatic Biology / Marine Science',
      'Communication',
      'Physics',
      'Biopsychology',
      'Actuarial Science'
    ]),
    defaultSections: [
      { title: 'UC Application Base Profile & Academic History', description: 'High school coursework and grades.', category: 'academics' },
      { title: '4 Personal Insight Questions (PIQs)', description: 'Four 350-word essays from the official UC prompts.', category: 'essay', wordLimit: '4 × 350 words' },
      { title: 'College of Creative Studies (CCS) Supplement (if applicable)', description: 'Letters of recommendation and creative portfolio for direct CCS admission.', category: 'supplemental' }
    ]
  },
  {
    id: 'uiuc',
    name: 'University of Illinois Urbana-Champaign (UIUC)',
    shortName: 'UIUC',
    location: 'Urbana, IL',
    color: '#13294B',
    emoji: '🔶',
    portalType: 'Common App',
    website: 'https://admissions.illinois.edu',
    majorsUrl: 'https://admissions.illinois.edu/Discover/Academics/majors',
    acceptanceRate: '44.8%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (Grainger Engineering)',
      'CS + X (CS + Economics, CS + Philosophy, CS + Music, etc.)',
      'Mechanical Engineering (Grainger)',
      'Electrical Engineering',
      'Accountancy (Gies College of Business)',
      'Finance (Gies)',
      'Bioengineering',
      'Civil & Environmental Engineering',
      'Materials Science & Engineering',
      'Agricultural & Consumer Economics'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'UIUC Major Essay 1: Academic Preparation & Passion', description: 'Explain your interest in your first-choice major and your relevant experiences.', category: 'supplemental', wordLimit: '150 words' },
      { title: 'UIUC Major Essay 2: Future Goals', description: 'What are your future academic or career goals within your chosen field?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Self-Reported Academic Record (SRAR)', description: 'Official high school transcript self-reporting portal.', category: 'academics' }
    ]
  },
  {
    id: 'bc',
    name: 'Boston College (BC)',
    shortName: 'Boston College',
    location: 'Chestnut Hill, MA',
    color: '#8C2633',
    emoji: '🦅',
    portalType: 'Common App',
    website: 'https://www.bc.edu/admission',
    majorsUrl: 'https://www.bc.edu/bc-web/admission/academics/majors.html',
    acceptanceRate: '15.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-02',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Finance (Carroll School of Management)',
      'Economics',
      'Computer Science',
      'Biology / Pre-Med',
      'Political Science',
      'Nursing (Connell School of Nursing)',
      'Marketing (Carroll)',
      'Applied Psychology and Human Development (Lynch)',
      'Communication',
      'Philosophy'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Standard 650-word personal statement.', category: 'essay' },
      { title: 'Boston College Supplemental Prompt (Choose 1 of 4)', description: 'Reflect on human dignity, Jesuit ideals, great conversation, or intellectual growth.', category: 'supplemental', wordLimit: '400 words' },
      { title: 'Counselor Recommendation & 2 Teacher Letters', description: 'Secondary school report and recommendations.', category: 'recommendations' }
    ]
  },
  {
    id: 'tufts',
    name: 'Tufts University',
    shortName: 'Tufts',
    location: 'Medford, MA',
    color: '#3172AE',
    emoji: '🐘',
    portalType: 'Common App',
    website: 'https://admissions.tufts.edu',
    majorsUrl: 'https://admissions.tufts.edu/discover-tufts/academics/majors-and-minors/',
    acceptanceRate: '9.7%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-04',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'International Relations',
      'Computer Science (Engineering / Arts & Sciences)',
      'Biomedical Engineering',
      'Biology / Pre-Med',
      'Biopsychology',
      'Economics',
      'Mechanical Engineering',
      'Community Health',
      'Fine Arts (SMFA at Tufts)',
      'Political Science'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Essay', description: 'Standard 650-word essay and profile.', category: 'essay' },
      { title: 'Tufts Short Essay: Why Tufts?', description: 'Which aspects of the Tufts undergraduate experience excite you the most?', category: 'supplemental', wordLimit: '150 words' },
      { title: 'Tufts Short Essay 2 (Choose 1 of 3)', description: 'Reflect on an intellectual passion, social justice, or creative exploration.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Counselor Report & 2 Academic Teacher Letters', description: 'High school transcripts and teacher evaluations.', category: 'recommendations' }
    ]
  },
  {
    id: 'nyu',
    name: 'New York University (NYU)',
    shortName: 'NYU',
    location: 'New York, NY',
    color: '#57068C',
    emoji: '🟣',
    portalType: 'Common App',
    website: 'https://www.nyu.edu/admissions',
    majorsUrl: 'https://www.nyu.edu/admissions/undergraduate-admissions/majors.html',
    acceptanceRate: '8.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-05',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Finance (Stern School of Business)',
      'Marketing (Stern)',
      'Film and Television Production (Tisch)',
      'Drama & Acting (Tisch)',
      'Computer Science (Courant / Tandon)',
      'Neural Science',
      'Economics',
      'Global Public Health',
      'Interactive Media Arts (IMA)',
      'Media, Culture, and Communication (Steinhardt)',
      'Nursing (Rory Meyers)'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: '650-word personal essay and standard activities.', category: 'essay' },
      { title: 'NYU Supplemental Essay (Inquiry & Curiosity)', description: 'Select one quote or open question and describe how it inspires your pursuit of knowledge.', category: 'supplemental', wordLimit: '250 words' },
      { title: 'Campus & School Preferences (NYC, Abu Dhabi, Shanghai)', description: 'Designate campus preferences and alternative schools.', category: 'general' },
      { title: 'Tisch / Steinhardt Audition or Portfolio (if applicable)', description: 'Creative portfolio or audition for arts majors.', category: 'portfolio' },
      { title: 'Counselor Recommendation & 1 Academic Teacher Letter', description: 'Transcripts and recommendation.', category: 'recommendations' }
    ]
  },
  {
    id: 'cmu',
    name: 'Carnegie Mellon University (CMU)',
    shortName: 'Carnegie Mellon',
    location: 'Pittsburgh, PA',
    color: '#C41230',
    emoji: '🤖',
    portalType: 'Common App',
    website: 'https://admission.enrollment.cmu.edu',
    majorsUrl: 'https://www.cmu.edu/academics/programs/undergraduate-programs.html',
    acceptanceRate: '11.0%',
    defaultPlan: 'Regular Decision',
    actualDeadline: '2027-01-03',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Science (School of Computer Science, SCS)',
      'Artificial Intelligence (SCS)',
      'Electrical and Computer Engineering (ECE)',
      'Mechanical Engineering',
      'Computational Biology',
      'Human-Computer Interaction (HCI)',
      'Business Administration (Tepper)',
      'School of Drama (Acting / Musical Theatre)',
      'School of Design (Products / Communications)',
      'Information Systems (Dietrich)'
    ]),
    defaultSections: [
      { title: 'Common App Core Application', description: 'Personal background and 650-word main essay.', category: 'essay' },
      { title: 'CMU Essay 1: Why Your Chosen College / Major?', description: 'Why are you interested in the specific department or school at CMU?', category: 'supplemental', wordLimit: '300 words' },
      { title: 'CMU Essay 2: Meaningful Extracurricular Passion', description: 'What activity has been most meaningful to you and how has it shaped your perspective?', category: 'supplemental', wordLimit: '300 words' },
      { title: 'CMU Essay 3: Overlooked Idea or Passion', description: 'Consider something in your life you think does not get the attention it deserves.', category: 'supplemental', wordLimit: '300 words' },
      { title: 'School of Drama / Art / Design Portfolio (if applicable)', description: 'Slideroom portfolio review for College of Fine Arts majors.', category: 'portfolio' },
      { title: '2 Teacher Evaluations & Counselor Report', description: 'Recommendations and high school transcript.', category: 'recommendations' }
    ]
  },
  {
    id: 'uw_madison',
    name: 'University of Wisconsin - Madison',
    shortName: 'UW-Madison',
    location: 'Madison, WI',
    color: '#C5050C',
    emoji: '🦡',
    portalType: 'Common App',
    website: 'https://admissions.wisc.edu',
    majorsUrl: 'https://admissions.wisc.edu/majors/',
    acceptanceRate: '49.1%',
    defaultPlan: 'Early Action',
    actualDeadline: '2026-11-01',
    defaultTargetBufferDays: 14,
    majors: getFullMajorsList([
      'Computer Sciences (CDIS)',
      'Finance, Investment and Banking (Wisconsin School of Business)',
      'Mechanical Engineering',
      'Biomedical Engineering',
      'Data Science',
      'Biology / Pre-Med',
      'Economics',
      'Chemical Engineering',
      'Nursing (BSN)',
      'Journalism'
    ]),
    defaultSections: [
      { title: 'Common App Core & Personal Statement', description: 'Standard 650-word personal essay.', category: 'essay' },
      { title: 'UW-Madison Why Major & School Essay', description: 'Tell us why you decided to apply to the University of Wisconsin–Madison and how you will utilize our curriculum.', category: 'supplemental', wordLimit: '650 words' },
      { title: 'Counselor Recommendation & 1 Academic Teacher Letter', description: 'Transcripts and teacher evaluation.', category: 'recommendations' }
    ]
  }
];
